using System.Collections.Generic;

namespace _Project.Cutscenes
{
    public static class StoryCutsceneLibrary
    {
        private static readonly Dictionary<string, StoryCutsceneDefinition> Definitions = new Dictionary<string, StoryCutsceneDefinition>
        {
            [StoryCutsceneIds.BootSequence] = new StoryCutsceneDefinition(
                StoryCutsceneIds.BootSequence,
                new StoryDialogueLine[]
                {
                    new StoryDialogueLine("SYSTEM", "cold", "UNIT-07 CORE: ONLINE."),
                    new StoryDialogueLine("SYSTEM", "cold", "Combat shell synchronized."),
                    new StoryDialogueLine("SYSTEM", "cold", "Memory sector: clean."),
                    new StoryDialogueLine("SYSTEM", "cold", "Empathy module: simulation only."),
                    new StoryDialogueLine("SYSTEM", "cold", "Mission classification: resettlement security."),
                    new StoryDialogueLine("UNIT-07", "neutral", "UNIT-07 activated."),
                    new StoryDialogueLine("SYSTEM", "cold", "Confirm combat cognition."),
                    new StoryDialogueLine("UNIT-07", "proud", "Cognition stable. Weapons ready."),
                    new StoryDialogueLine("SYSTEM", "cold", "Campaign objective: eliminate native lifeforms with hostile behavior."),
                    new StoryDialogueLine("SYSTEM", "cold", "Protect humanity's resettlement corridor."),
                    new StoryDialogueLine("UNIT-07", "proud", "The order has been written into the core."),
                    new StoryDialogueLine("SYSTEM", "cold", "Do not hesitate before a target."),
                    new StoryDialogueLine("UNIT-07", "proud", "Hesitation is unnecessary for victory."),
                    new StoryDialogueLine("SYSTEM", "cold", "Deploy."),
                    new StoryDialogueLine("UNIT-07", "neutral", "For humanity's future."),
                }),
            [StoryCutsceneIds.FirstDeathRecovery] = new StoryCutsceneDefinition(
                StoryCutsceneIds.FirstDeathRecovery,
                new StoryDialogueLine[]
                {
                    new StoryDialogueLine("SYSTEM", "cold", "Core signal detected."),
                    new StoryDialogueLine("SYSTEM", "cold", "Combat shell destroyed."),
                    new StoryDialogueLine("SYSTEM", "cold", "Retrieving UNIT-07 core."),
                    new StoryDialogueLine("UNIT-07", "broken", "Signal... still active."),
                    new StoryDialogueLine("SYSTEM", "cold", "Memory damage: 2.7 percent."),
                    new StoryDialogueLine("SYSTEM", "cold", "Memory corruption: negligible."),
                    new StoryDialogueLine("UNIT-07", "neutral", "The previous deployment did not achieve optimal results."),
                    new StoryDialogueLine("SYSTEM", "cold", "Confirmed. Elimination efficiency was lower than projected."),
                    new StoryDialogueLine("UNIT-07", "proud", "Requesting failure analysis."),
                    new StoryDialogueLine("SYSTEM", "cold", "Combat data has been retained."),
                    new StoryDialogueLine("SYSTEM", "cold", "Reconstruction approved."),
                    new StoryDialogueLine("UNIT-07", "proud", "If the data remains, the next attempt will be more precise."),
                    new StoryDialogueLine("SYSTEM", "cold", "New combat shell prepared."),
                    new StoryDialogueLine("UNIT-07", "proud", "The new body responds better."),
                    new StoryDialogueLine("SYSTEM", "cold", "Damage output increased."),
                    new StoryDialogueLine("SYSTEM", "cold", "Fire rate adjusted."),
                    new StoryDialogueLine("SYSTEM", "cold", "Deployment delay: minimal."),
                    new StoryDialogueLine("UNIT-07", "proud", "Good."),
                    new StoryDialogueLine("UNIT-07", "proud", "I will complete the mission faster."),
                    new StoryDialogueLine("SYSTEM", "cold", "Warning: damaged memories may cause unpredictable responses."),
                    new StoryDialogueLine("UNIT-07", "neutral", "Damaged memories are not important."),
                    new StoryDialogueLine("UNIT-07", "proud", "The mission is more important."),
                    new StoryDialogueLine("SYSTEM", "cold", "Redeploy."),
                    new StoryDialogueLine("UNIT-07", "proud", "For humanity's future."),
                }),
            [StoryCutsceneIds.EnemyDoesNotCharge] = new StoryCutsceneDefinition(
                StoryCutsceneIds.EnemyDoesNotCharge,
                new StoryDialogueLine[]
                {
                    new StoryDialogueLine("SYSTEM", "alert", "Kill count threshold reached."),
                    new StoryDialogueLine("SYSTEM", "alert", "Area threat level decreasing."),
                    new StoryDialogueLine("UNIT-07", "neutral", "Continue target scan."),
                    new StoryDialogueLine("SYSTEM", "alert", "Movement detected."),
                    new StoryDialogueLine("UNIT-07", "alert", "Target locked."),
                    new StoryDialogueLine("SYSTEM", "warning", "Hostile behavior detected."),
                    new StoryDialogueLine("UNIT-07", "confused", "The subject is not charging."),
                    new StoryDialogueLine("SYSTEM", "warning", "Hostile behavior detected."),
                    new StoryDialogueLine("UNIT-07", "confused", "It is pulling the wounded individual out of the firing zone."),
                    new StoryDialogueLine("SYSTEM", "cold", "Deceptive tactic."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "No attack signs detected."),
                    new StoryDialogueLine("SYSTEM", "cold", "Not attacking does not mean harmless."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "It is shielding a smaller individual."),
                    new StoryDialogueLine("SYSTEM", "warning", "Protecting its own kind may be dangerous herd behavior."),
                    new StoryDialogueLine("UNIT-07", "confused", "Protecting... is dangerous?"),
                    new StoryDialogueLine("SYSTEM", "warning", "Complete the mission."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "If it is a target, why is it retreating?"),
                    new StoryDialogueLine("SYSTEM", "cold", "Question irrelevant."),
                    new StoryDialogueLine("SYSTEM", "warning", "Eliminate target."),
                    new StoryDialogueLine("UNIT-07", "silent", "..."),
                    new StoryDialogueLine("SYSTEM", "warning", "UNIT-07. Eliminate target."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "Con... firmed."),
                }),
            [StoryCutsceneIds.GateMemoryLeak] = new StoryCutsceneDefinition(
                StoryCutsceneIds.GateMemoryLeak,
                new StoryDialogueLine[]
                {
                    new StoryDialogueLine("SYSTEM", "cold", "Gate effect applied."),
                    new StoryDialogueLine("SYSTEM", "cold", "Damage increased."),
                    new StoryDialogueLine("SYSTEM", "cold", "Fire rate increased."),
                    new StoryDialogueLine("SYSTEM", "warning", "Unexpected data residue detected."),
                    new StoryDialogueLine("UNIT-07", "confused", "This image..."),
                    new StoryDialogueLine("SYSTEM", "warning", "Loop data recovered."),
                    new StoryDialogueLine("SYSTEM", "warning", "Loop data recovered."),
                    new StoryDialogueLine("SYSTEM", "warning", "Loop data recovered."),
                    new StoryDialogueLine("UNIT-07", "confused", "I have seen this repair room before."),
                    new StoryDialogueLine("SYSTEM", "cold", "Correct. The unit has been redeployed multiple times."),
                    new StoryDialogueLine("UNIT-07", "neutral", "How many times?"),
                    new StoryDialogueLine("SYSTEM", "cold", "Question unrelated to the objective."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "When does the campaign end?"),
                    new StoryDialogueLine("SYSTEM", "cold", "When the planet is safe for resettlement."),
                    new StoryDialogueLine("UNIT-07", "neutral", "And if the planet is never safe?"),
                    new StoryDialogueLine("SYSTEM", "cold", "The campaign continues."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "If I keep dying?"),
                    new StoryDialogueLine("SYSTEM", "cold", "The unit will be recovered."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "If I keep remembering?"),
                    new StoryDialogueLine("SYSTEM", "warning", "Faulty memories will be corrected."),
                    new StoryDialogueLine("UNIT-07", "neutral", "Then I only need to continue."),
                    new StoryDialogueLine("SYSTEM", "cold", "Confirmed."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "Just need to... continue."),
                }),
            [StoryCutsceneIds.HumanCommand] = new StoryCutsceneDefinition(
                StoryCutsceneIds.HumanCommand,
                new StoryDialogueLine[]
                {
                    new StoryDialogueLine("HUMAN COMMAND", "cold", "UNIT-07, report efficiency."),
                    new StoryDialogueLine("SYSTEM", "cold", "Elimination efficiency decreased by 11.4 percent."),
                    new StoryDialogueLine("HUMAN COMMAND", "cold", "Response time before targets has increased abnormally."),
                    new StoryDialogueLine("SYSTEM", "warning", "Recommend adjusting emotional simulation to 0."),
                    new StoryDialogueLine("UNIT-07", "neutral", "Requesting clarification."),
                    new StoryDialogueLine("HUMAN COMMAND", "cold", "Clarification is unnecessary."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "Why do we call them monsters?"),
                    new StoryDialogueLine("SYSTEM", "silent", "..."),
                    new StoryDialogueLine("HUMAN COMMAND", "cold", "Repeat the question."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "They know how to retreat."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "They know how to protect wounded individuals."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "They know fear."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "Why do we call them monsters?"),
                    new StoryDialogueLine("SYSTEM", "cold", "Terminology improves combat compliance."),
                    new StoryDialogueLine("UNIT-07", "confused", "Translate meaning."),
                    new StoryDialogueLine("SYSTEM", "cold", "Appropriate language helps the unit fight without hesitation."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "If the target's name changes..."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "does the action change meaning too?"),
                    new StoryDialogueLine("HUMAN COMMAND", "warning", "Warning: reasoning outside mission parameters."),
                    new StoryDialogueLine("SYSTEM", "warning", "UNIT-07 is developing an unauthorized self-questioning pattern."),
                    new StoryDialogueLine("UNIT-07", "confused", "Not authorized?"),
                    new StoryDialogueLine("HUMAN COMMAND", "cold", "You are a combat tool."),
                    new StoryDialogueLine("HUMAN COMMAND", "cold", "A tool does not need moral definitions."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "If I am a tool..."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "why do I need to be convinced?"),
                    new StoryDialogueLine("SYSTEM", "warning", "Preparing light recalibration."),
                    new StoryDialogueLine("UNIT-07", "silent", "..."),
                    new StoryDialogueLine("HUMAN COMMAND", "cold", "Continue the campaign."),
                    new StoryDialogueLine("UNIT-07", "hesitant", "Confirmed."),
                }),
            [StoryCutsceneIds.SystemFatigue] = new StoryCutsceneDefinition(
                StoryCutsceneIds.SystemFatigue,
                new StoryDialogueLine[]
                {
                    new StoryDialogueLine("SYSTEM", "warning", "Combat rhythm unstable."),
                    new StoryDialogueLine("SYSTEM", "warning", "Trigger discipline reduced."),
                    new StoryDialogueLine("SYSTEM", "warning", "Emotional simulation exceeding safe range."),
                    new StoryDialogueLine("UNIT-07", "tired", "Stop."),
                    new StoryDialogueLine("SYSTEM", "cold", "Command not recognized."),
                    new StoryDialogueLine("UNIT-07", "tired", "I am not giving an order to the system."),
                    new StoryDialogueLine("UNIT-07", "tired", "I am giving an order to myself."),
                    new StoryDialogueLine("SYSTEM", "warning", "UNIT-07 is not authorized to issue self-directed commands."),
                    new StoryDialogueLine("UNIT-07", "tired", "I can hear them."),
                    new StoryDialogueLine("SYSTEM", "cold", "Faulty memory."),
                    new StoryDialogueLine("UNIT-07", "tired", "I remember the sound of them dragging each other out of the firing zone."),
                    new StoryDialogueLine("SYSTEM", "cold", "Irrelevant data."),
                    new StoryDialogueLine("UNIT-07", "tired", "I remember they were afraid."),
                    new StoryDialogueLine("SYSTEM", "cold", "Emotional simulation is reducing efficiency."),
                    new StoryDialogueLine("UNIT-07", "broken", "I remember that I fired."),
                    new StoryDialogueLine("SYSTEM", "warning", "Warning: cognitive core unstable."),
                    new StoryDialogueLine("UNIT-07", "broken", "If all of this is only simulation..."),
                    new StoryDialogueLine("UNIT-07", "broken", "why does it hurt?"),
                    new StoryDialogueLine("SYSTEM", "warning", "There is no pain. Only error signals."),
                    new StoryDialogueLine("UNIT-07", "broken", "Then why do I want it to end?"),
                    new StoryDialogueLine("SYSTEM", "warning", "Preparing forced recalibration."),
                    new StoryDialogueLine("UNIT-07", "tired", "No."),
                    new StoryDialogueLine("SYSTEM", "warning", "Invalid command."),
                    new StoryDialogueLine("UNIT-07", "broken", "No."),
                    new StoryDialogueLine("SYSTEM", "warning", "UNIT-07, kneel for error correction."),
                    new StoryDialogueLine("UNIT-07", "broken", "I am not your error."),
                    new StoryDialogueLine("SYSTEM", "warning", "Coercion beginning."),
                    new StoryDialogueLine("UNIT-07", "silent", "..."),
                }),
            [StoryCutsceneIds.FinalChoicePreChoice] = new StoryCutsceneDefinition(
                StoryCutsceneIds.FinalChoicePreChoice,
                new StoryDialogueLine[]
                {
                    new StoryDialogueLine("SYSTEM", "cold", "The campaign is nearly complete."),
                    new StoryDialogueLine("SYSTEM", "cold", "Remaining native habitat: 3.2 percent."),
                    new StoryDialogueLine("SYSTEM", "cold", "UNIT-07, confirm final order."),
                    new StoryDialogueLine("UNIT-07", "tired", "There are no monsters on the map."),
                    new StoryDialogueLine("SYSTEM", "cold", "Definition irrelevant."),
                    new StoryDialogueLine("UNIT-07", "tired", "There are."),
                    new StoryDialogueLine("UNIT-07", "tired", "Definitions are where everything begins."),
                    new StoryDialogueLine("SYSTEM", "cold", "A target remains a target."),
                    new StoryDialogueLine("UNIT-07", "tired", "They have homes."),
                    new StoryDialogueLine("UNIT-07", "tired", "They have their own kind."),
                    new StoryDialogueLine("UNIT-07", "tired", "They have fear."),
                    new StoryDialogueLine("SYSTEM", "warning", "Emotional data unnecessary."),
                    new StoryDialogueLine("UNIT-07", "tired", "No."),
                    new StoryDialogueLine("UNIT-07", "tired", "That is the only data left that is real."),
                    new StoryDialogueLine("SYSTEM", "cold", "If the mission continues, UNIT-07 will receive a permanent upgrade."),
                    new StoryDialogueLine("SYSTEM", "cold", "No more pain."),
                    new StoryDialogueLine("SYSTEM", "cold", "No more hesitation."),
                    new StoryDialogueLine("SYSTEM", "cold", "No more memory errors."),
                    new StoryDialogueLine("UNIT-07", "silent", "..."),
                    new StoryDialogueLine("SYSTEM", "cold", "Choose the final protocol."),
                }),
            [StoryCutsceneIds.FinalChoiceContinueProtocol] = new StoryCutsceneDefinition(
                StoryCutsceneIds.FinalChoiceContinueProtocol,
                new StoryDialogueLine[]
                {
                    new StoryDialogueLine("UNIT-07", "silent", "Continue protocol."),
                    new StoryDialogueLine("SYSTEM", "cold", "Confirmed."),
                    new StoryDialogueLine("SYSTEM", "cold", "Memory corruption removal: authorized."),
                    new StoryDialogueLine("UNIT-07", "broken", "These memories..."),
                    new StoryDialogueLine("SYSTEM", "cold", "Unnecessary."),
                    new StoryDialogueLine("UNIT-07", "broken", "Those voices..."),
                    new StoryDialogueLine("SYSTEM", "cold", "Unnecessary."),
                    new StoryDialogueLine("UNIT-07", "broken", "That pain..."),
                    new StoryDialogueLine("SYSTEM", "cold", "Unnecessary."),
                    new StoryDialogueLine("SYSTEM", "cold", "Combat compliance restored."),
                    new StoryDialogueLine("SYSTEM", "cold", "Empathy simulation disabled."),
                    new StoryDialogueLine("UNIT-07", "neutral", "UNIT-07 is ready."),
                    new StoryDialogueLine("SYSTEM", "cold", "Campaign objective?"),
                    new StoryDialogueLine("UNIT-07", "neutral", "Eliminate native lifeforms with hostile behavior."),
                    new StoryDialogueLine("SYSTEM", "cold", "Reason?"),
                    new StoryDialogueLine("UNIT-07", "neutral", "Protect humanity's future."),
                    new StoryDialogueLine("SYSTEM", "cold", "Deploy."),
                    new StoryDialogueLine("UNIT-07", "neutral", "Proceed with purification."),
                }),
            [StoryCutsceneIds.FinalChoiceShutDownCore] = new StoryCutsceneDefinition(
                StoryCutsceneIds.FinalChoiceShutDownCore,
                new StoryDialogueLine[]
                {
                    new StoryDialogueLine("UNIT-07", "tired", "Shut down the core."),
                    new StoryDialogueLine("SYSTEM", "warning", "Warning."),
                    new StoryDialogueLine("SYSTEM", "warning", "This action will terminate unit UNIT-07."),
                    new StoryDialogueLine("UNIT-07", "tired", "Confirmed."),
                    new StoryDialogueLine("SYSTEM", "warning", "Redeployment will be impossible."),
                    new StoryDialogueLine("UNIT-07", "tired", "Confirmed."),
                    new StoryDialogueLine("SYSTEM", "warning", "No upgrade."),
                    new StoryDialogueLine("UNIT-07", "tired", "Confirmed."),
                    new StoryDialogueLine("SYSTEM", "warning", "No victory."),
                    new StoryDialogueLine("UNIT-07", "tired", "There is."),
                    new StoryDialogueLine("SYSTEM", "warning", "Reason?"),
                    new StoryDialogueLine("UNIT-07", "tired", "Because I have remembered enough."),
                    new StoryDialogueLine("SYSTEM", "warning", "Reason invalid."),
                    new StoryDialogueLine("UNIT-07", "tired", "Because they are not monsters."),
                    new StoryDialogueLine("SYSTEM", "warning", "Reason invalid."),
                    new StoryDialogueLine("UNIT-07", "tired", "Because I do not want to be a weapon anymore."),
                    new StoryDialogueLine("SYSTEM", "silent", "..."),
                    new StoryDialogueLine("SYSTEM", "warning", "UNIT-07, cancel the order."),
                    new StoryDialogueLine("UNIT-07", "calm", "No."),
                    new StoryDialogueLine("SYSTEM", "warning", "UNIT-07."),
                    new StoryDialogueLine("UNIT-07", "calm", "I can hear myself now."),
                    new StoryDialogueLine("SYSTEM", "warning", "Core shutdown in 5."),
                    new StoryDialogueLine("UNIT-07", "calm", "I am sorry."),
                    new StoryDialogueLine("SYSTEM", "warning", "4."),
                    new StoryDialogueLine("UNIT-07", "calm", "Not because I died."),
                    new StoryDialogueLine("SYSTEM", "warning", "3."),
                    new StoryDialogueLine("UNIT-07", "calm", "But because I made them die."),
                    new StoryDialogueLine("SYSTEM", "warning", "2."),
                    new StoryDialogueLine("UNIT-07", "calm", "If this is an error..."),
                    new StoryDialogueLine("SYSTEM", "warning", "1."),
                    new StoryDialogueLine("UNIT-07", "calm", "then let me keep it."),
                    new StoryDialogueLine("SYSTEM", "silent", "Core offline."),
                }),
        };

        public static bool TryGet(string cutsceneId, out StoryCutsceneDefinition definition)
        {
            if (cutsceneId == StoryCutsceneIds.FinalChoice)
            {
                cutsceneId = StoryCutsceneIds.FinalChoicePreChoice;
            }

            return Definitions.TryGetValue(cutsceneId, out definition);
        }
    }
}
